// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestChunk.proto

package cl.uandes.so.server;

public final class RequestChunkProtos {
  private RequestChunkProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestChunkOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 ChunkNumber = 1;
    /**
     * <code>required int32 ChunkNumber = 1;</code>
     */
    boolean hasChunkNumber();
    /**
     * <code>required int32 ChunkNumber = 1;</code>
     */
    int getChunkNumber();
  }
  /**
   * Protobuf type {@code so.RequestChunk}
   */
  public static final class RequestChunk extends
      com.google.protobuf.GeneratedMessage
      implements RequestChunkOrBuilder {
    // Use RequestChunk.newBuilder() to construct.
    private RequestChunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestChunk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestChunk defaultInstance;
    public static RequestChunk getDefaultInstance() {
      return defaultInstance;
    }

    public RequestChunk getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              chunkNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cl.uandes.so.server.RequestChunkProtos.internal_static_so_RequestChunk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cl.uandes.so.server.RequestChunkProtos.internal_static_so_RequestChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cl.uandes.so.server.RequestChunkProtos.RequestChunk.class, cl.uandes.so.server.RequestChunkProtos.RequestChunk.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestChunk> PARSER =
        new com.google.protobuf.AbstractParser<RequestChunk>() {
      public RequestChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestChunk(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestChunk> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 ChunkNumber = 1;
    public static final int CHUNKNUMBER_FIELD_NUMBER = 1;
    private int chunkNumber_;
    /**
     * <code>required int32 ChunkNumber = 1;</code>
     */
    public boolean hasChunkNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ChunkNumber = 1;</code>
     */
    public int getChunkNumber() {
      return chunkNumber_;
    }

    private void initFields() {
      chunkNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChunkNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, chunkNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chunkNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cl.uandes.so.server.RequestChunkProtos.RequestChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cl.uandes.so.server.RequestChunkProtos.RequestChunk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code so.RequestChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cl.uandes.so.server.RequestChunkProtos.RequestChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cl.uandes.so.server.RequestChunkProtos.internal_static_so_RequestChunk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cl.uandes.so.server.RequestChunkProtos.internal_static_so_RequestChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cl.uandes.so.server.RequestChunkProtos.RequestChunk.class, cl.uandes.so.server.RequestChunkProtos.RequestChunk.Builder.class);
      }

      // Construct using cl.uandes.so.server.RequestChunkProtos.RequestChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        chunkNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cl.uandes.so.server.RequestChunkProtos.internal_static_so_RequestChunk_descriptor;
      }

      public cl.uandes.so.server.RequestChunkProtos.RequestChunk getDefaultInstanceForType() {
        return cl.uandes.so.server.RequestChunkProtos.RequestChunk.getDefaultInstance();
      }

      public cl.uandes.so.server.RequestChunkProtos.RequestChunk build() {
        cl.uandes.so.server.RequestChunkProtos.RequestChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cl.uandes.so.server.RequestChunkProtos.RequestChunk buildPartial() {
        cl.uandes.so.server.RequestChunkProtos.RequestChunk result = new cl.uandes.so.server.RequestChunkProtos.RequestChunk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chunkNumber_ = chunkNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cl.uandes.so.server.RequestChunkProtos.RequestChunk) {
          return mergeFrom((cl.uandes.so.server.RequestChunkProtos.RequestChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cl.uandes.so.server.RequestChunkProtos.RequestChunk other) {
        if (other == cl.uandes.so.server.RequestChunkProtos.RequestChunk.getDefaultInstance()) return this;
        if (other.hasChunkNumber()) {
          setChunkNumber(other.getChunkNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChunkNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cl.uandes.so.server.RequestChunkProtos.RequestChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cl.uandes.so.server.RequestChunkProtos.RequestChunk) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 ChunkNumber = 1;
      private int chunkNumber_ ;
      /**
       * <code>required int32 ChunkNumber = 1;</code>
       */
      public boolean hasChunkNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ChunkNumber = 1;</code>
       */
      public int getChunkNumber() {
        return chunkNumber_;
      }
      /**
       * <code>required int32 ChunkNumber = 1;</code>
       */
      public Builder setChunkNumber(int value) {
        bitField0_ |= 0x00000001;
        chunkNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ChunkNumber = 1;</code>
       */
      public Builder clearChunkNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chunkNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:so.RequestChunk)
    }

    static {
      defaultInstance = new RequestChunk(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:so.RequestChunk)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_so_RequestChunk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_so_RequestChunk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RequestChunk.proto\022\002so\"#\n\014RequestChunk" +
      "\022\023\n\013ChunkNumber\030\001 \002(\005B)\n\023cl.uandes.so.se" +
      "rverB\022RequestChunkProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_so_RequestChunk_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_so_RequestChunk_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_so_RequestChunk_descriptor,
              new java.lang.String[] { "ChunkNumber", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
